apply plugin: "java"

repositories.mavenCentral()
dependencies.annotationProcessor rootProject//.files("build/libs/jabel-${rootProject.version}.jar")

// Force java 1.8
compileJava{
    targetCompatibility = JavaVersion.VERSION_1_8
    sourceCompatibility = JavaVersion.VERSION_25
    options.encoding = "UTF-8"
    options.release = 8
    //options.compilerArgs += "-Xplugin:jabel"

    // For debugging
    options.fork = true
    options.forkOptions.jvmArgs += "-XX:-OmitStackTraceInFastThrow"
}

sourceSets.main.java.srcDirs = ["src"]
ext.mainClassName = "Main"
jar.manifest.attributes["Main-Class"] = project.mainClassName

task run(dependsOn: classes, type: JavaExec){
    mainClass = project.mainClassName
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
    workingDir = buildDir
    
    // Force using jre8 to be sure
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
