package com.github.bsideup.jabel;

import com.sun.source.util.*;
import com.sun.tools.javac.code.*;
import com.sun.tools.javac.code.Symbol.*;
import com.sun.tools.javac.code.Type.*;
import com.sun.tools.javac.comp.Operators;
import com.sun.tools.javac.tree.*;
import com.sun.tools.javac.tree.JCTree.*;
import com.sun.tools.javac.util.*;


/**
 * Replaces {@link MatchException} catch clauses, generated by the compiler for
 * record patterns unpacking, by {@link RuntimeException}.
 */
public class RecordPatternRetrofittingTaskListener implements TaskListener {
    private boolean MATCH_EXCEPTION_PRESENT = SwitchRetrofittingTaskListener.MATCH_EXCEPTION_PRESENT;

    final TreeMaker make;
    final Symtab syms;
    final Names names;
    final MethodSymbol runtimeExceptionConstructor;
    final OperatorSymbol opCONCAT;

    public RecordPatternRetrofittingTaskListener(Context context) {
        make = TreeMaker.instance(context);
        syms = Symtab.instance(context);
        names = Names.instance(context);

        runtimeExceptionConstructor = getRuntimeExceptionConstructor();
        opCONCAT = SwitchRetrofittingTaskListener.resolveBinary(
                Operators.instance(context),
                make.Literal(0),
                Tag.PLUS,
                syms.stringType,
                syms.stringType
        );
    }

    @Override
    public void started(TaskEvent e) {
        if (!MATCH_EXCEPTION_PRESENT) return;
        if (e.getKind() != TaskEvent.Kind.GENERATE) return;
        if (!(e.getCompilationUnit() instanceof JCCompilationUnit)) return;
        new MatchExceptionFixer().translate((JCCompilationUnit) e.getCompilationUnit());
    }

    @Override
    public void finished(TaskEvent e) {
        if (!MATCH_EXCEPTION_PRESENT) return;
        if (e.getKind() != TaskEvent.Kind.ANALYZE) return;
        // Creates the virtual symbol after analyze, so the user-code cannot reference it
        injectMatchException();
    }

    public class MatchExceptionFixer extends TreeTranslator {
        @Override
        public void visitBlock(JCBlock tree) {
            JCCatch c = SwitchRetrofittingTaskListener.getPatternMatchingCatchHandler(tree);
            if (c != null) {
                if (isMatchException(c.param.vartype)) {
                    c.param.vartype = make.QualIdent(syms.runtimeExceptionType.tsym)
                                          .setType(syms.runtimeExceptionType);
                    if (c.param.sym != null) c.param.sym.type = syms.runtimeExceptionType;
                }
                JCTree last = result;
                c.body = translate(c.body);
                result = last;
            }
            super.visitBlock(tree);
        }

        @Override
        public void visitNewClass(JCNewClass tree) {
            super.visitNewClass(tree);
            if (!isMatchException(tree.clazz)) return;

            if (runtimeExceptionConstructor != null) {
                tree.clazz = make.QualIdent(syms.runtimeExceptionType.tsym).setType(syms.runtimeExceptionType);
                tree.type = syms.runtimeExceptionType;
                tree.constructor = runtimeExceptionConstructor;
            }
            if (opCONCAT != null) {
                tree.args.head = make.Binary(
                        Tag.PLUS,
                        make.Literal("MatchException: Record-pattern unpacking failed: "),
                        tree.args.head
                ).setType(syms.stringType);
                ((JCBinary) tree.args.head).operator = opCONCAT;
            } else {
                tree.args.head = make.Literal("MatchException: record-pattern unpacking failed");
            }
        }
    }

    public boolean isMatchException(JCTree t) {
        if (t == null) return false;
        // TODO find a better way?
        switch (t.toString()) {
            case "java.lang.MatchException":
            case "MatchException":
                return true;
            default:
                return false;
        }
    }

    /**
     * Registers a virtual {@link MatchException} symbol to make the compiler happy.
     */
    public void injectMatchException() {
        ClassSymbol cs = (ClassSymbol) syms.matchExceptionType.tsym;
        if (cs == null) return;
        if (cs.classfile != null) {
            // Do nothing if already exists in the classpath to avoid changing the user code
            MATCH_EXCEPTION_PRESENT = false;
            return;
        }
        if (cs.members_field != null && !cs.members_field.isEmpty()) return;

        // Fill the current symbol
        cs.flags_field = Flags.PUBLIC;
        ClassType ct = new ClassType(Type.noType, List.nil(), cs);
        ct.supertype_field = syms.runtimeExceptionType;
        cs.type = ct;
        cs.members_field = Scope.WriteableScope.create(cs);

        // Only create the constructor used by TransPatterns
        cs.members_field.enter(new MethodSymbol(
                Flags.PUBLIC,
                names.init,
                new MethodType(
                        List.of(syms.stringType, syms.throwableType),
                        syms.voidType,
                        List.nil(),
                        syms.methodClass
                ),
                cs
        ));
        cs.completer = Completer.NULL_COMPLETER;
    }

    public MethodSymbol getRuntimeExceptionConstructor() {
        for (Symbol sym : syms.runtimeExceptionType.tsym.members().getSymbols()) {
            if (sym.kind != Kinds.Kind.MTH) continue;
            if (sym.name != names.init) continue;
            MethodSymbol m = (MethodSymbol) sym;
            if (m.params().size() != 2) continue;
            // TODO: check for actual types?
            return m;
        }
        return null;
    }
}
